controllers/MainController.php
<?php

namespace app\controllers;

use app\models\Blogers;
use app\models\GiveHasUser;
use app\models\Gives;
use app\models\LoginForm;
use Yii;
use app\models\User;
use app\models\search\UserSearch;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MainController implements the CRUD actions for User model.
 */
class MainController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = 'user';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $blogers = Blogers::find()->where(['is_star' => true])->all();
        $top_give = Gives::findOne(['is_main' => true, 'status' => Gives::STATUS_NEW]);
        $gives = Gives::find()->limit(5)->where(['is_main' => false])->andWhere(['status' => Gives::STATUS_NEW])->orderBy('date_start desc')->all();
        return $this->render('index',
            [
                'blogers' => $blogers,
                'top_give' => $top_give,
                'gives' => $gives,
            ]
        );
    }

    public function actionGives($bloger = false)
    {
        $gives = Gives::find()->where(['status' => Gives::STATUS_NEW]);
        if ($bloger) {
            $gives->andWhere(['bloger_id' => $bloger]);
        }
        return $this->render('gives', ['gives' => $gives->all()]);
    }

    public function actionGivesCompleted($bloger = false)
    {
        $gives = Gives::find()->where(['status' => Gives::STATUS_END])->andWhere(['is_main' => false]);
        if ($bloger) {
            $gives->andWhere(['bloger_id' => $bloger]);
        }
        $bloger = Blogers::findOne($bloger);
        return $this->render('gives_completed', ['gives' => $gives->all(), 'bloger' => $bloger]);
    }

    public function actionBuyGive($id)
    {
        $GHU = new GiveHasUser();
        $GHU->give_id = $id;
        $GHU->user_id = Yii::$app->user->id;
        $GHU->save(false);
        return $this->redirect('/main/thank-page');
    }

    public function actionThankPage()
    {
        return $this->render('thank-page');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if (Yii::$app->request->isAjax) {
            if ($model->load(Yii::$app->request->post())) {
                if ($model->login()) {
                    if (Yii::$app->user->identity->role == User::ROLE_ADMIN) {
                        return $this->redirect(Url::to(['/user/index']));
                    }
                    return $this->redirect(Url::to(['/main/gives']));
                } else {
                    Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
                    return \yii\widgets\ActiveForm::validate($model);
                }
            }
        }
        $model->password = '';
        if (empty($model->getErrors())) {
            echo 'Ок';
        }
    }

    public function actionRecoveryPassword()
    {
        $user = User::findOne(['email' => Yii::$app->request->post('User')['email']]);
        if ($user) {
            $user->password = Yii::$app->security->generateRandomString(10);
            if ($user->save(false)) {
                Yii::$app->mailer
                    ->compose('recovery', ['user' => $user])
                    ->setSubject('Ваш новый пароль')
                    ->setTo($user->email)
                    ->send();
            }
        } else {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            return \yii\widgets\ActiveForm::validate($user);
        }

    }

    public function actionConsultation()
    {
        Yii::$app->session->set('sent_popup_opener', 'sent_popup_opener');
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionRegistration()
    {
        $model = new User();
        if ($model->load(Yii::$app->request->post())) {
            $model->status = null;
            $model->role = User::ROLE_USER;
            if ($model->save()) {
                Yii::$app->mailer
                    ->compose('registration_admin', ['user' => $model])
                    ->setSubject('Новая заявка на участие в GiveCorp')
                    ->setTo('admin@givecorp.ru')
                    ->send();

                return $this->render('success_registration', ['model' => $model]);
            }
        }
        return $this->render('registration', ['model' => $model]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/blocks/header.php
<header>
    <div class="wrapper">
        <div class="header"><a class="header_logo logo logo_black" href="/">givecorp</a>
            <div class="header_button"><a class="button button_transparent_blue getconsultation_opener" href="#">
                    Получить консультацию</a></div>
            <div class="header_right"><a class="header_login <?= Yii::$app->user->isGuest ? 'login_opener' : '' ?>"
                                         href="<?= Yii::$app->user->isGuest ? '#' : \yii\helpers\Url::to(['/site/logout']) ?>"><?= Yii::$app->user->isGuest ? 'Войти' : 'Выйти' ?></a><a
                    class="header_menu menu_opener" href="#"><span></span><span
                        class="header_menu_middle"></span><span></span></a></div>
        </div>
    </div>
</header>

views/blocks/table_popup.php
<?php
/**
 * @var $give \app\models\Gives
 */
?>
<div class="table_popup table_popup_top table_popup_bloger"><span
            class="table_popup_close"><svg
                viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" fill="rgb(77, 115, 215)"
                                                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.518,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.480,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
                                        </svg></span>
    <div class="table_popup_bloger_photo"
         style="background-image: url(img/<?= $give->bloger->avatar ?>)"></div>
    <div class="table_popup_bloger_name"><?= $give->bloger->name ?></div>
    <a class="table_popup_bloger_inst" href="<?= $give->bloger->instagram ?>"><?= $give->bloger->instagram_name ?></a>
    <div class="table_popup_bloger_sub"><?= $give->bloger->count_subscribes ?>
        подписчиков
    </div>
    <div class="table_popup_bloger_text"><?= $give->bloger->text ?>
    </div>
    <a class="table_popup_bloger_link"
       href="<?= \yii\helpers\Url::to(['/main/gives-completed', 'bloger' => $give->bloger_id]) ?>">Проведенные
        гивы</a>
    <div class="table_popup_bloger_bottom">
        <div class="table_popup_bloger_bottom_next">Следующий
            гив: С <?= date('d-m-Y', strtotime($give->date_start)) ?><br>
            По <?= date('d-m-Y', strtotime($give->date_end)) ?></div>
        <div class="table_popup_bloger_bottom_cost">
                                        <span>Мест: <?= (count($give->giveHasUsers) + $give->plus_subscriber ? $give->plus_subscriber : 0) ?>
                                            /<?= $give->count_seats ?></span><span>Стоимость: <?= $give->all_cost ?>
                руб.</span>
        </div>
        <a class="link"
           href="<?= Yii::$app->user->isGuest ? \yii\helpers\Url::to(['/main/registration']) : \yii\helpers\Url::to(['/main/gives']) ?>">Участвовать
            в гиве</a>
    </div>
</div>