controllers/MainController.php
<?php

namespace app\controllers;

use app\models\Blogers;
use app\models\GiveHasUser;
use app\models\Gives;
use app\models\LoginForm;
use Yii;
use app\models\User;
use app\models\search\UserSearch;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MainController implements the CRUD actions for User model.
 */
class MainController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = 'user';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $blogers = Blogers::find()->where(['is_star' => true])->all();
        $top_give = Gives::findOne(['is_main' => true, 'status' => Gives::STATUS_NEW]);
        $gives = Gives::find()->limit(5)->where(['is_main' => false])->andWhere(['status' => Gives::STATUS_NEW])->orderBy('date_start desc')->all();
        return $this->render('index',
            [
                'blogers' => $blogers,
                'top_give' => $top_give,
                'gives' => $gives,
            ]
        );
    }

    public function actionGives($bloger = false)
    {
        $gives = Gives::find()->where(['status' => Gives::STATUS_NEW]);
        if ($bloger) {
            $gives->andWhere(['bloger_id' => $bloger]);
        }
        return $this->render('gives', ['gives' => $gives->all()]);
    }

    public function actionGivesCompleted($bloger = false)
    {
        $gives = Gives::find()->where(['status' => Gives::STATUS_END])->andWhere(['is_main' => false]);
        if ($bloger) {
            $gives->andWhere(['bloger_id' => $bloger]);
        }
        $bloger = Blogers::findOne($bloger);
        return $this->render('gives_completed', ['gives' => $gives->all(), 'bloger' => $bloger]);
    }

    public function actionBuyGive($id)
    {
        $GHU = new GiveHasUser();
        $GHU->give_id = $id;
        $GHU->user_id = Yii::$app->user->id;
        $GHU->save(false);
        return $this->redirect('/main/thank-page');
    }

    public function actionThankPage()
    {
        return $this->render('thank-page');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if (Yii::$app->request->isAjax) {
            if ($model->load(Yii::$app->request->post())) {
                if ($model->login()) {
                    if (Yii::$app->user->identity->role == User::ROLE_ADMIN) {
                        return $this->redirect(Url::to(['/user/index']));
                    }
                    return $this->redirect(Url::to(['/main/gives']));
                } else {
                    Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
                    return \yii\widgets\ActiveForm::validate($model);
                }
            }
        }
        $model->password = '';
        if (empty($model->getErrors())) {
            echo 'Ок';
        }
    }

    public function actionRecoveryPassword()
    {
        $user = User::findOne(['email' => Yii::$app->request->post('User')['email']]);
        if ($user) {
            $user->password = Yii::$app->security->generateRandomString(10);
            if ($user->save(false)) {
                Yii::$app->mailer
                    ->compose('recovery', ['user' => $user])
                    ->setSubject('Ваш новый пароль')
                    ->setTo($user->email)
                    ->send();
            }
        } else {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            return \yii\widgets\ActiveForm::validate($user);
        }

    }

    public function actionConsultation()
    {
        Yii::$app->session->set('sent_popup_opener', 'sent_popup_opener');
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionRegistration()
    {
        $model = new User();
        if ($model->load(Yii::$app->request->post())) {
            $model->status = null;
            $model->role = User::ROLE_USER;
            if ($model->save()) {
                Yii::$app->mailer
                    ->compose('registration_admin', ['user' => $model])
                    ->setSubject('Новая заявка на участие в GiveCorp')
                    ->setTo('admin@givecorp.ru')
                    ->send();

                return $this->render('success_registration', ['model' => $model]);
            }
        }
        return $this->render('registration', ['model' => $model]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/popup/popups.php
<?php

use yii\widgets\ActiveForm;

?>
<div class="getconsultation_popup popup">
    <div class="popup_close">
        <svg viewBox="0 0 16 16">
            <path fill-rule="evenodd" fill="rgb(255, 255, 255)"
                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.519,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.481,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
        </svg>
    </div>
    <div class="getconsultation_center">
        <div class="getconsultation_inner">
            <h2>Получить бесплатную консультацию</h2>
            <div class="getconsultation_text">Нажимая кнопку «Отправить» вы даете согласие на обработку персональных
                данных
            </div>
            <?php $form = ActiveForm::begin([
                'id' => 'consultation',
                'action' => \yii\helpers\Url::to(['/main/consultation']),
                'validateOnChange' => true,
                'validateOnSubmit' => true,
                'enableClientValidation' => true,
                'options' => ['class' => 'getconsultation_form', 'name' => 'sign_in'],
                'fieldConfig' => [
                    'options' => ['class' => ''],
                    'template' => "{label}{input}{error}",
                ],
            ]); ?>
            <div class="getconsultation_form_row">
                <?= $form->field(new \app\models\User(), 'first_name')->textInput(['class' => 'sing_input', 'placeholder' => 'Ваше имя'])->label(false) ?>
                <?= $form->field(new \app\models\User(), 'phone')->textInput(['class' => 'sing_input', 'placeholder' => 'Номер вашего телефона'])->label(false) ?>
            </div>
            <button class="button button_transparent_white">Отправить</button>
            <?php ActiveForm::end(); ?>
            <div class="getconsultation_text_mobile">Нажимая кнопку «Отправить» вы даете согласие на обработку
                персональных данных
            </div>
        </div>
    </div>
</div>
<div class="main_menu">
    <div class="main_menu_inner">
        <div class="main_menu_close">
            <svg viewBox="0 0 16 16">
                <path fill-rule="evenodd" fill="rgb(255, 255, 255)"
                      d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.519,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.481,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
            </svg>
        </div>
        <div class="main_menu_content">
            <ul>
                <li><a href="#">Участвовать в гиве</a></li>
                <li><a href="#">Блогерам</a></li>
                <li><a href="#">Брендам и магазинам</a></li>
            </ul>
            <div class="main_menu_content_mobile"><a class="<?= Yii::$app->user->isGuest ? 'login_opener' : '' ?>"
                                                     href="<?= Yii::$app->user->isGuest ? '#' : \yii\helpers\Url::to(['/site/logout']) ?>"><?= Yii::$app->user->isGuest ? 'Войти' : 'Выйти' ?></a><a
                        class="getconsultation_opener" onclick="$('.main_menu').hide()">Получить консультацию</a></div>
            <div class="main_menu_write"><a class="button button_transparent_white" href="#">Написать нам в whatsapp</a>
            </div>
            <a class="main_menu_link" href="mailto: support@givecorp.ru">support@givecorp.ru</a>
        </div>
    </div>
</div>
<div class="main_menu_bg"></div>
<div class="login_popup popup">
    <div class="popup_close">
        <svg viewBox="0 0 16 16">
            <path fill-rule="evenodd" fill="rgb(255, 255, 255)"
                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.519,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.481,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
        </svg>
    </div>
    <div class="getconsultation_center">
        <div class="getconsultation_inner">
            <h2>Войти в личный кабинет</h2>
            <div class="getconsultation_text"></div>
            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'action' => \yii\helpers\Url::to(['/main/login']),
                'validateOnChange' => true,
                'validateOnSubmit' => true,
                'enableClientValidation' => true,
                'enableAjaxValidation' => true,

                'options' => ['class' => 'getconsultation_form', 'name' => 'sign_in'],
                'fieldConfig' => [
                    'options' => ['class' => ''],
                    'template' => "{label}{input}{error}",
                ],
            ]); ?>
            <div class="getconsultation_form_row">
                <?= $form->field(new \app\models\LoginForm(), 'email')->textInput(['class' => 'sing_input', 'placeholder' => 'Логин (email)'])->label(false) ?>
                <?= $form->field(new \app\models\LoginForm(), 'password')->passwordInput(['class' => 'sing_input', 'placeholder' => 'Пароль'])->label(false) ?>
            </div>
            <button class="button button_transparent_white">Войти</button>
            <?php ActiveForm::end(); ?>
            <a class="getconsultation_text forgot_popup_opener" href="#">Забыли пароль?</a>
            <a class="getconsultation_text_mobile forgot_popup_opener" href="#">Забыли пароль?</a>
        </div>
    </div>
</div>
<div class="video_popup popup">
    <div class="popup_close" id="pausevideo">
        <svg viewBox="0 0 16 16">
            <path fill-rule="evenodd" fill="rgb(255, 255, 255)"
                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.519,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.481,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
        </svg>
    </div>
    <div class="getconsultation_center">
        <div class="getconsultation_inner">
            <div class="video_inner">
                <div class="video_player" id="video_player"></div>
            </div>
        </div>
    </div>
</div>

<div class="sent_popup popup">
    <div class="popup_close">
        <svg viewBox="0 0 16 16">
            <path fill-rule="evenodd" fill="rgb(255, 255, 255)"
                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.519,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.481,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
        </svg>
    </div>
    <div class="getconsultation_center">
        <div class="getconsultation_inner">
            <h2>Заявка на консультацию отправлена!</h2>
            <div class="sent_content">
                <div class="section_signup_successtext">В течение 3-х часов с вами свяжется <br>менеджер для уточнения
                    деталей
                </div>
                <a class="button button_transparent_white" href="#">Продолжить</a>
            </div>
        </div>
    </div>
</div>
<div class="forgot_popup popup">
    <div class="popup_close">
        <svg viewBox="0 0 16 16">
            <path fill-rule="evenodd" fill="rgb(255, 255, 255)"
                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.519,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.481,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
        </svg>
    </div>
    <div class="getconsultation_center">
        <div class="getconsultation_inner">
            <h2>Восстановить пароль</h2>
            <div class="getconsultation_text"></div>
            <?php $form = ActiveForm::begin([
                'id' => 'recover',
                'action' => \yii\helpers\Url::to(['/main/recovery-password']),
                'validateOnChange' => true,
                'validateOnSubmit' => true,
                'enableAjaxValidation' => true,
                'enableClientValidation' => true,
                'options' => ['class' => 'getconsultation_form', 'name' => 'sign_in'],
                'fieldConfig' => [
                    'options' => ['class' => ''],
                    'template' => "{label}{input}{error}",
                ],
            ]); ?>
            <div class="getconsultation_form_row">
                <?= $form->field(new \app\models\User(), 'email')->textInput(['class' => 'tac', 'placeholder' => 'Ваш e-mail'])->label(false) ?>
            </div>
            <button class="button button_transparent_white forgot_popup_sent_opener">Отправить</button>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<div class="forgot_popup_sent popup">
    <div class="popup_close">
        <svg viewBox="0 0 16 16">
            <path fill-rule="evenodd" fill="rgb(255, 255, 255)"
                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.519,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.481,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
        </svg>
    </div>
    <div class="getconsultation_center">
        <div class="getconsultation_inner">
            <h2>На Ваш e-mail отправлен новый пароль <br>для входа в личный кабинет</h2><a
                    class="button button_transparent_white" href="#">Продолжить</a>
        </div>
    </div>
</div>